/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logica;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Admin-Alex
 */
public class jPanel_3 extends javax.swing.JPanel {

    /**
     * Creates new form jPanel_3
     */
    public String tipoFecha;

    public String getTipoFecha() {
        return tipoFecha;
    }

    public void setTipoFecha(String tipoFecha) {
        this.tipoFecha = tipoFecha;
    }

    

    

    public void comprobarFecha() {
        
        switch (tipoFecha){
            
            case "dia":
                int num1 = (Integer) jSpinner1.getValue();
                jLabelTipo.setText("Dia:");
                if (num1 < 0 || num1 > 31) {
                    mensajeFecha.setText("Solo numeros del 1 al 31");
                }else{
                    mensajeFecha.setText("");
                }
                break;
            case "mes":
                int num2 = (Integer) jSpinner1.getValue();
                jLabelTipo.setText("Mes:");
                if (num2 < 0 || num2 > 12) {
                    mensajeFecha.setText("Solo numeros del 1 al 12");
                }else{
                    mensajeFecha.setText("");
                }
                break;
            case "año":
                jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1980, 1980, 2010, 1));
                int num3 = (Integer) jSpinner1.getValue();
                jLabelTipo.setText("Año:");
                if (num3 < 1980 || num3 > 2010) {
                    mensajeFecha.setText("Solo años correctos");
                }else{
                    mensajeFecha.setText("");
                }
                break;
        }
        
        

    }

    public jPanel_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabelTipo = new javax.swing.JLabel();
        mensajeFecha = new javax.swing.JLabel();

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        mensajeFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajeFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensajeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        comprobarFecha();
    }//GEN-LAST:event_jSpinner1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel mensajeFecha;
    // End of variables declaration//GEN-END:variables
}
