/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logica;

/**
 *
 * @author Admin-Alex
 */
public class jPanel_1 extends javax.swing.JPanel {

    /**
     * Creates new form jPanel_1
     */
    public String tipoValidacion;

    public String getTipoValidacion() {
        return tipoValidacion;
    }

    public void setTipoValidacion(String tipoValidacion) {
        this.tipoValidacion = tipoValidacion;
    }
    
    
    public void validar(){
        if(textValidar.getText().length() == 8){
            tipoValidacion = "DNI";
            labelValidar.setText("DNI:");
        }
        if(textValidar.getText().length() == 9){
            tipoValidacion = "NUMERO";
            labelValidar.setText("NUMERO:");
        }
        if(textValidar.getText().length() == 5){
            tipoValidacion = "CP";
            labelValidar.setText("CODIGO POSTAL:");
        }
        switch (tipoValidacion){
            case "DNI":
                if (textValidar.getText().length()!=8) {
                    labelValidar.setText("DNI INCORRECTO");
                }
                else{
                    labelValidar.setText("DNI CORRECTO");
                }
                break;
            case "NUMERO":
                if (textValidar.getText().length()!=9) {
                    labelValidar.setText("Numero INCORRECTO");
                }
                else{
                    labelValidar.setText("Numero CORRECTO");
                }
                break;
            case "CP":
                if (textValidar.getText().length()!=5) {
                    labelValidar.setText("Codigo postal INCORRECTO");
                }
                else{
                    labelValidar.setText("Codigo postal CORRECTO");
                }
                break;
        }
    }
    
    public jPanel_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textValidar = new javax.swing.JTextField();
        labelValidar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        textValidar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textValidarFocusLost(evt);
            }
        });

        jLabel1.setText("Identificacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(textValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textValidar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textValidarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textValidarFocusLost
        validar();
    }//GEN-LAST:event_textValidarFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelValidar;
    private javax.swing.JTextField textValidar;
    // End of variables declaration//GEN-END:variables
}
